name: .NET Core Build
on:
  push:
    branches:
      - master # Default release branch
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Dotnet Build
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.x'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'    
      - run: |
          cd ./src/Specification
          dotnet build -f netstandard1.6 --configuration Release
          dotnet build -f netstandard2.0 --configuration Release
          dotnet build -f netstandard2.1 --configuration Release
          dotnet build -f net5.0 --configuration Release
          dotnet build -f net6.0 --configuration Release    
          
  tests:
    name: Dotnet Tests
    strategy:
      matrix:
        service:
        - Specification.IntegrationTests
        - Specification.Tests
    runs-on: ubuntu-latest
    steps:
    - name: Test
    - run: |
        dotnet test ./tests/${{ matrix.service }} /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov --logger:trx -r TestResults
    - name: Publish coverage report to coveralls.io   
      uses: coverallsapp/github-action@master   
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        parallel: true
        path-to-lcov: ./tests/${{ matrix.service }}/TestResults/coverage.info
      
  coveralls-finished:
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
