name: .NET Core Build
on:
  push:
    branches:
      - master # Default release branch
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Dotnet Side by Side testing sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.x'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - run: |
          cd ./src/Specification
          dotnet build --configuration Release
      - run: |
          ls ./tests/*.Tests -d | xargs -L1 dotnet test --logger:trx -r test-results
