name: Continuous Integration

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "!master"
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet: [
          { frameworktest: netcoreapp2.1, fbuild: netstandard2.0, version: 2.1.x },
          { frameworktest: netcoreapp3.1, fbuild: netstandard2.1, version: 3.1.x },
          { frameworktest: net5.0, fbuild: net5.0, version: 5.x },
          { frameworktest: net6.0, fbuild: net6.0, version: 6.x },
        ]

    name: ${{ matrix.dotnet.framework }} – run tests

    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet.version }}

      - name: Run build
        run: |
          cd ./src/Specification
          dotnet build -f ${{ matrix.dotnet.fbuild }} --configuration Release
          
      - name: Run tests
        run: |    
          dotnet test --configuration Release --framework ${{ matrix.dotnet.frameworktest }} ./tests/Specification.IntegrationTests/Specification.IntegrationTests.csproj /p:Framework=${{ matrix.dotnet.frameworktest }}
          dotnet test --configuration Release --framework ${{ matrix.dotnet.frameworktest }} ./tests/Specification.Tests/Specification.Tests.csproj /p:Framework=${{ matrix.dotnet.frameworktest }}
