name: Continuous Integration

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "!master"
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet: [
          { framework: netcoreapp2.1, frameworkbuild: netstandard2.0, version: 2.1.x },
          { framework: netcoreapp3.1, frameworkbuild: netstandard2.1, version: 3.1.x },
          { framework: net5.0, frameworkbuild: net5.0, version: 5.x },
          { framework: net6.0, frameworkbuild: net6.0, version: 6.x },
        ]

    name: ${{ matrix.dotnet.framework }} – run tests

    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet.version }}

      - name: Run build
        run: |
          cd ./src/Specification
          dotnet build --configuration Release --framework ${{ matrix.dotnet.frameworkbuild }} /p:Framework=${{ matrix.dotnet.framework }}
          
      - name: Run tests
        run: |    
          dotnet test --configuration Release --framework ${{ matrix.dotnet.framework }} ./tests/Specification.IntegrationTests/Specification.IntegrationTests.csproj /p:Framework=${{ matrix.dotnet.framework }}
          dotnet test --configuration Release --framework ${{ matrix.dotnet.framework }} ./tests/Specification.Tests/Specification.Tests.csproj /p:Framework=${{ matrix.dotnet.framework }}
