name: Continuous Integration

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "!master"
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.x
          
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Run build
        run: |
          cd ./src/Specification
          dotnet build --configuration Release --framework netstandard2.0 /p:Framework=netcoreapp2.1
          dotnet build --configuration Release --framework netstandard2.1 /p:Framework=netcoreapp3.1
          dotnet build --configuration Release --framework net5.0 /p:Framework=net5.0
          dotnet build --configuration Release --framework net6.0 /p:Framework=net6.0
          
      - name: Run tests
        run: |    
          dotnet test --configuration Release --framework netcoreapp2.1 ./tests/Specification.Tests/Specification.Tests.csproj /p:Framework=netcoreapp2.1
          dotnet test --configuration Release --framework netcoreapp3.1 ./tests/Specification.Tests/Specification.Tests.csproj /p:Framework=netcoreapp3.1
          dotnet test --configuration Release --framework net5.0 ./tests/Specification.Tests/Specification.Tests.csproj /p:Framework=net5.0
          dotnet test --configuration Release --framework net6.0 ./tests/Specification.Tests/Specification.Tests.csproj /p:Framework=net6.0
          dotnet test --configuration Release --framework netcoreapp3.1 ./tests/Specification.IntegrationTests/Specification.IntegrationTests.csproj /p:Framework=netcoreapp3.1
          dotnet test --configuration Release --framework net5.0 ./tests/Specification.IntegrationTests/Specification.IntegrationTests.csproj /p:Framework=net5.0
          dotnet test --configuration Release --framework net6.0 ./tests/Specification.IntegrationTests/Specification.IntegrationTests.csproj /p:Framework=net6.0
