name: Continuous Integration

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "!master"
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet: [
          { framework: netstandard2.0, netframework: netcoreapp2.1, version: 2.1.x },
          { framework: netstandard2.1, netframework: netcoreapp3.1, version: 3.1.x },
          { framework: netstandard2.1, netframework: net5.0, version: 5.0.x },
          { framework: netstandard2.1, netframework: net6.0, version: 6.0.x }
        ]

    name: ${{ matrix.dotnet.framework }} – run tests

    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet.version }}

      - name: Run tests
        run: |
          dotnet test --configuration Release ./tests/Specification.IntegrationTests/Specification.IntegrationTests.csproj /p:Framework=${{ matrix.dotnet.framework }}
          dotnet test --configuration Release ./tests/Specification.Tests/Specification.Tests.csproj /p:Framework=${{ matrix.dotnet.framework }}
