name: master

on:
  push:
    branches:
      - master

jobs:
  build-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet: [
          { framework: netstandard2.1, conditionframework: netcoreapp3.1, version: 3.1.x },
          { framework: net5.0, conditionframework: net5.0, version: 5.0.x },
          { framework: net6.0, conditionframework: net6.0, version: 6.0.x },
        ]

    name: ${{ matrix.dotnet.framework }} – run tests

    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet.version }}

      - name: Run build
        run: |
          dotnet build --configuration Release --framework ${{ matrix.dotnet.framework }} ./src/Specification/Specification.csproj /p:Framework=${{ matrix.dotnet.conditionframework }}

      - name: Run UnitTests
        run: |    
          dotnet test --configuration Release --framework ${{ matrix.dotnet.conditionframework }} ./tests/Specification.Tests/Specification.Tests.csproj /p:Framework=${{ matrix.dotnet.conditionframework }}

      - name: Run IntegrationTests
        run: |    
          dotnet test --configuration Release --framework ${{ matrix.dotnet.conditionframework }} ./tests/Specification.IntegrationTests/Specification.IntegrationTests.csproj /p:Framework=${{ matrix.dotnet.conditionframework }}


  coveralls-started:
    needs: build-tests

    name: Calculate Coverage 

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Run UnitTests
        run:     
          dotnet test --configuration Release --framework net6.0 ./tests/Specification.Tests/Specification.Tests.csproj /p:Framework=net6.0 /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov --logger:trx -r TestResults
      
      - name: Run IntegrationTests
        run:    
          dotnet test --configuration Release --framework net6.0 ./tests/Specification.IntegrationTests/Specification.IntegrationTests.csproj /p:Framework=net6.0 /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov --logger:trx -r TestResults
      
      - name: Publish coverage report to coveralls.io   
        uses: coverallsapp/github-action@master   
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-Specification.Tests
          parallel: true
          path-to-lcov: ./tests/Specification.Tests/TestResults/coverage.net6.0.info

      - name: Publish coverage report to coveralls.io   
        uses: coverallsapp/github-action@master   
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-Specification.IntegrationTests
          parallel: true
          path-to-lcov: ./tests/Specification.IntegrationTests/TestResults/coverage.net6.0.info
      

  coveralls-finished:
    needs: coveralls-started

    name: Coveralls Publish

    runs-on: ubuntu-latest

    steps:
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
          

  release:
    needs: coveralls-finished

    name: Create release
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Extract version
        id: extract-version
        run: |
          version=$(cat ./src/Specification/Specification.csproj | grep "<VersionPrefix>" | sed -e "s/ *<\/*VersionPrefix>//g")
          echo "Package version: $version"
          if [ -z "${version// }" ]; then exit 1; fi
          echo "::set-output name=package_version::$version"
      - name: Extract latest commit message
        id: latest-commit
        run: |
          echo "${{ github.ref }}"
          echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.event.after }})"
      - uses: jwalton/gh-find-current-pr@v1
        id: find-pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.extract-version.outputs.package_version }}
          release_name: Release v${{ steps.extract-version.outputs.package_version }}
          body: ${{ steps.find-pr.outputs.body || steps.latest-commit.outputs.message }}
          draft: true
          prerelease: false     
          
